apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-efkx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-efkx@sha256:38a147f578a07f66f9e35b66d60cd919e00899b59bf9485ee2a3b64a3463e1c2
        name: my-nodejs
        resources: {}
status: {}
